In [2]:
import json
import pandas as pd
import numpy as np

### 处理course数据

In [2]:
course_df = pd.read_csv('F:\\mooccubex\\csv\\course_em.csv')

In [3]:
course_df_ids = course_df["embedding_id"]

In [4]:
course_df_ids_min = np.min(course_df_ids)

In [5]:
course_df_ids_max = np.max(course_df_ids)

In [6]:
course_df_names = course_df["name"]

In [7]:
course_df_names_unique = np.unique(course_df_names)

In [8]:
course_df_fields = course_df["field"].dropna()

In [9]:
course_df_fields_join = ','.join(course_df_fields)

In [10]:
course_df_fields_split_list = course_df_fields_join.split(",")

In [11]:
course_df_fields_split_list_unique = np.unique(course_df_fields_split_list)

In [12]:
course_o = {
    "id_min":course_df_ids_min,
    "id_max":course_df_ids_max,
    "names_unique":course_df_names_unique.tolist(),
    "fields_unique":course_df_fields_split_list_unique.tolist()
}

### 处理user数据

In [13]:
user_df = pd.read_csv('F:\\mooccubex\\csv\\user.csv')

In [14]:
def custom_function(x):
    return int(x.split("_")[1])

In [15]:
user_df_ids = user_df["id"].apply(custom_function)

In [16]:
user_df_ids_min = np.min(user_df_ids)
user_df_ids_max = np.max(user_df_ids)

In [17]:
user_df_ids_names = user_df["name"].dropna()

In [18]:
def handle_names(x):
    x = str(x)
    x = x.replace("\n","")
    x = x.replace("\t","")
    return x;

In [19]:
user_df_ids_names  =user_df_ids_names.apply(handle_names)

In [20]:
user_df_ids_names_list = user_df_ids_names.tolist()

In [21]:
user_df_ids_names_list_unique = list(set(user_df_ids_names_list)) 

In [22]:
user_df_schools_unique = list(set(user_df_schools))

NameError: name 'user_df_schools' is not defined

In [104]:
def get_yaer(x):
    return int(str(x).split(".")[0])

In [105]:
user_df_years = (user_df["year_of_birth"].dropna()).apply(get_yaer)

In [106]:
user_df_years_unique = list(set(user_df_years))

In [107]:
user_df_years_unique_less_2024 =  [ x for x in user_df_years_unique if x <= 2024]

In [200]:
user_o={
    "id_min":user_df_ids_min,
    "id_max":user_df_ids_max,
    "names_unique":user_df_ids_names_list_unique,
    "schools_unique":user_df_schools_unique,
    "years_unique":user_df_years_unique_less_2024
}

### 处理 school 数据

In [112]:
school_df = pd.read_csv('F:\\mooccubex\\csv\\school.csv')

In [114]:
school_df_ids = school_df["id"].apply(custom_function)

In [116]:
school_df_ids_min = np.min(school_df_ids)
school_df_ids_max = np.max(school_df_ids)

In [121]:
school_df_names  = school_df["name"].apply(handle_names)

In [124]:
school_df_names_list_unique = list(set(school_df_names)) 

In [127]:
school_df_names_en =  school_df["name_en"].apply(handle_names)

In [128]:
school_df_names_en_list_unique = list(set(school_df_names_en)) 

In [131]:
school_df_signs  = school_df["sign"].apply(handle_names)

In [132]:
school_df_signs_list_unique = list(set(school_df_signs))

In [134]:
school_df_mottos = school_df["motto"].dropna()

In [136]:
school_df_mottos_list_unique  = list(set(school_df_mottos))

In [202]:
school_o = {
    "id_min":school_df_ids_min,
    "id_max":school_df_ids_max,
    "names_unique":school_df_names_list_unique,
    "names_en_unique":school_df_names_en_list_unique,
    "signs_unique":school_df_signs_list_unique,
    "mottos_unique":school_df_mottos_list_unique
}

### 处理 teacher

In [140]:
teacher_df = pd.read_csv('F:\\mooccubex\\csv\\teacher.csv')

In [142]:
teacher_df_ids = teacher_df["id"].apply(custom_function)

In [144]:
teacher_df_ids_min = np.min(teacher_df_ids)
teacher_df_ids_max = np.max(teacher_df_ids)

In [148]:
teacher_df_names  = teacher_df["name"].apply(handle_names)
teacher_df_names_list_unique = list(set(teacher_df_names)) 

In [155]:
teacher_df_names_en =  (teacher_df["name_en"]).apply(handle_names).dropna()
teacher_df_names_en_list_unique = list(set(teacher_df_names_en)) 

In [163]:
teacher_df_titles =list(set( (teacher_df["job_title"]).apply(handle_names).dropna()))

In [164]:
teacher_df_titles_jion = ','.join(teacher_df_titles)

In [166]:
teacher_df_titles_split = teacher_df_titles_jion.split(",")

In [168]:
teacher_df_titles_list_unique = list(set(teacher_df_titles_split))

In [173]:
teacher_df_orgs_list_unique =list(set( teacher_df["org_name"].apply(handle_names).dropna()))

In [203]:
teacher_o = {
    "id_min":teacher_df_ids_min,
    "id_max":teacher_df_ids_max,
    "names_unique":teacher_df_names_list_unique,
    "names_en_unique":teacher_df_names_en_list_unique,
    "titles_unique":teacher_df_titles_list_unique,
    "orgs_unique":teacher_df_orgs_list_unique
}

### 处理 course-field 数据

In [178]:
cf_df = pd.read_csv('F:\\mooccubex\\csv\\course-field.csv')

In [180]:
cf_df_fields = cf_df["field"]

In [184]:
def hanlde_cf_field(x):
    x = x.replace("[","")
    x = x.replace("]","")
    x = x.replace("'","")
    return x;

In [185]:
cf_df_fields_handle = cf_df_fields.apply(hanlde_cf_field)

In [187]:
cf_df_fields_handle_join = ','.join(cf_df_fields_handle)

In [188]:
cf_df_fields_handle_split = cf_df_fields_handle_join.split(",")

In [189]:
cf_df_fields_handle_list_unique = list(set(cf_df_fields_handle_split))

In [204]:
cf_o = {
    "fields_unique":cf_df_fields_handle_list_unique
}

### 合并保存

In [205]:
mooc_o = {
    "course":course_o,
    "use":user_o,
    "school":school_o,
    "teacher_o":teacher_o,
    "course-field":cf_o
}

In [207]:
with open('F:\\mooccubex\\csv\\data_overview.json', 'w', encoding='utf-8') as file:
    json.dump(mooc_o, file,ensure_ascii=False, indent=4)

### 处理 problem

In [11]:
problem_df = pd.read_csv('F:\\mooccubex\\csv\\problem\\vector_1.csv')

In [12]:
problem_df

,id,exercise_id,language,content,score,type,typetext,content_vector
0,1731,Ex_856,Chinese,《资治通鉴》是一部____史书。,1.0,1,单选题,"[0.39206284284591675, -0.01713784784078598, 0...."
1,1732,Ex_856,Chinese,《资治通鉴》原名____，后由____赐名“资治通鉴”。,1.0,1,单选题,"[0.17630906403064728, 0.11642387509346008, -0...."
2,1733,Ex_856,Chinese,“三家分晋”中“三家”具体指：,1.0,1,单选题,"[0.09372518211603165, 0.26491445302963257, -0...."
3,1734,Ex_856,Chinese,智伯联合韩、魏的军队攻打赵氏时，赵襄子选择退守的阵地是：,1.0,1,单选题,"[0.25193318724632263, 0.25246575474739075, 0.0..."
4,1735,Ex_856,Chinese,智、韩、魏联军攻赵时魏国的国都是：,1.0,1,单选题,"[0.22098691761493683, 0.198500856757164, 0.078..."
...,...,...,...,...,...,...,...,...
34811,126334,Ex_98723,Chinese,在旅游团出站前，地陪持接站标志，站在出口处醒目位置，热情迎候旅游团。接小型旅游团或无领队、全...,1.0,6,判断题,"[-0.12103244662284851, 0.011650942265987396, -..."
34812,126335,Ex_98723,Chinese,地陪应提前（ ）抵达交通口岸，与司机商定车辆停放位置。,1.0,1,单选题,"[-0.1349629908800125, 0.027143092826008797, 0...."
34813,126336,Ex_98723,Chinese,旅游团抵达前，地陪应做好如下工作：（ ）。,2.0,2,多选题,"[0.2686191499233246, 0.008727191016077995, 0.2..."
34814,126337,Ex_98723,Chinese,转移是指导游员带领旅游者离开机场（车站、码头），前往所下榻饭店的过程，这是导游员给客人留下良...,1.0,6,判断题,"[0.10417768359184265, -0.0781116634607315, 0.1..."


In [13]:
problem_df_zh = pd.read_csv('F:\\mooccubex\\csv\\problem\\problem_zh.csv')

C:\Users\wushengfa\AppData\Local\Temp\ipykernel_16004\2609211272.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  problem_df_zh = pd.read_csv('F:\\mooccubex\\csv\\problem\\problem_zh.csv')


In [14]:
problem_df_zh

,id,exercise_id,language,content,score,type,typetext
0,1731,Ex_856,Chinese,《资治通鉴》是一部____史书。,1.0,1.0,单选题
1,1732,Ex_856,Chinese,《资治通鉴》原名____，后由____赐名“资治通鉴”。,1.0,1.0,单选题
2,1733,Ex_856,Chinese,“三家分晋”中“三家”具体指：,1.0,1.0,单选题
3,1734,Ex_856,Chinese,智伯联合韩、魏的军队攻打赵氏时，赵襄子选择退守的阵地是：,1.0,1.0,单选题
4,1735,Ex_856,Chinese,智、韩、魏联军攻赵时魏国的国都是：,1.0,1.0,单选题
...,...,...,...,...,...,...,...
1536772,8223477,Ex_8357669,Chinese,系统地阐释了关于社会主义阶段的理论，完整概括中国共产党在社会主义初级阶段为“一个中心 两个基...,2.0,1.0,单选题
1536773,8223478,Ex_8357669,Chinese,1985年2月，下列哪一地区没有被开辟为沿海经济开发区？,2.0,1.0,单选题
1536774,8223479,Ex_8357669,Chinese,1981 年 6 月，中共十一届六中全会通过了（ ），科学地评价了毛泽东和毛泽东思想的历史...,2.0,1.0,单选题
1536775,8223480,Ex_8357669,Chinese,1980年5月，邓小平发表《关于农村政策的谈话》，肯定了哪种生产这种形式，指出它不会影响我们...,2.0,1.0,单选题


In [39]:
problem_df_zh["score"].dropna().unique()

array([  1. ,   2. ,  10. ,   5. ,   1.5,   3. ,   4. ,   6. ,   0.5,
        30. ,  35. ,  20. ,  15. ,  25. ,   7. ,   8. ,  50. ,  40. ,
        60. , 100. ,   5.5,   3.5,   0. ,  11. ,   9. ,  13. ,   2.5,
        16. ,  55. ,  12. ,  12.5,   0.8,   4.5,   0.2,   0.3,  33. ,
        34. ,  80. ,  70. ,  14. ,  17. ,  18. ])

In [38]:
problem_df_en["score"].dropna().unique()

array([  1. ,   2. ,  10. ,   3. ,  20. ,   5. ,   1.5,   2.5,  15. ,
         0. ,  30. ,   4. ,   6. ,   7. ,  50. ,  16. ,  11.5,  11. ,
         8. ,  12. ,  25. ,   0.5,  40. , 100. ])

In [26]:
problem_df_en = pd.read_csv('F:\\mooccubex\\csv\\problem\\problem_en.csv')

In [37]:
type(problem_df_zh["score"].dropna().unique())

numpy.ndarray

In [43]:
np.unique(np.concatenate([problem_df_zh["score"].dropna().unique(),problem_df_en["score"].dropna().unique()]))

array([  0. ,   0.2,   0.3,   0.5,   0.8,   1. ,   1.5,   2. ,   2.5,
         3. ,   3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   7. ,   8. ,
         9. ,  10. ,  11. ,  11.5,  12. ,  12.5,  13. ,  14. ,  15. ,
        16. ,  17. ,  18. ,  20. ,  25. ,  30. ,  33. ,  34. ,  35. ,
        40. ,  50. ,  55. ,  60. ,  70. ,  80. , 100. ])

In [27]:
problem_df_en

,id,exercise_id,language,content,score,type,typetext
0,7690,Ex_6808,English,He ______ the firm’s success to the efforts of...,1.0,1,单选题
1,7691,Ex_6808,English,Poor organization was certainly a _____ factor...,1.0,1,单选题
2,7692,Ex_6808,English,Acid rain is not straightforwardly _____ to th...,1.0,1,单选题
3,7693,Ex_6808,English,"Heat, cold, tactile and other sensations _____...",1.0,1,单选题
4,7694,Ex_6809,English,Xinchun returned from abroad a different man. ...,1.0,1,单选题
...,...,...,...,...,...,...,...
136609,8420963,Ex_8621996,English,The endorsor of of Insurance Policy is Shangha...,2.0,6,判断题
136610,8420964,Ex_8621996,English,CREDIT NUMBER AND NAME OF ISSUING BANK are no ...,2.0,6,判断题
136611,8420965,Ex_8621996,English,The Bill of Lading must be endorsed in blank b...,2.0,6,判断题
136612,8420966,Ex_8621996,English,The goods description of goods in the Bill of ...,2.0,6,判断题


In [45]:
np.unique(np.concatenate([problem_df_zh["typetext"].dropna().unique(),problem_df_en["typetext"].dropna().unique()]))

array(['主观题', '判断题', '单选题', '填空题', '多选题', '投票题', '编程题'], dtype=object)

In [46]:
problem_o = {
    "id_min":1731,
    "id_max":8420895,
    "exercise_id_min":856,
    "exercise_id_max":8621956,
    "language_unique":['Chinese','English'],
    "score_unique":np.unique(np.concatenate([problem_df_zh["score"].dropna().unique(),problem_df_en["score"].dropna().unique()])).tolist(),
    "type_unique":np.unique(np.concatenate([problem_df_zh["type"].dropna().unique(),problem_df_en["type"].dropna().unique()])).tolist(),
    "typetext_unique":np.unique(np.concatenate([problem_df_zh["typetext"].dropna().unique(),problem_df_en["typetext"].dropna().unique()])).tolist()
}

In [47]:

# JSON文件路径
file_path = 'F:\\mooccubex\\csv\\data_overview.json'

# 读取JSON文件并转换为字典
with open(file_path, 'r', encoding='utf-8') as file:
    data = json.load(file)


IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [50]:
del data["course-field"]

In [52]:
 data.update({'teacher': data.pop('teacher_o')})

In [55]:
for key, value in data.items():
    print(f'Key: {key}')

Key: course
Key: use
Key: school
Key: teacher
Key: problem


In [54]:
data["problem"] = problem_o

### 处理comment

In [59]:
comment_df = pd.read_csv('F:\\mooccubex\\csv\\comment\\tensor_40.csv')

In [60]:
comment_df

,id,user_id,text,create_time,text_tersor
0,Cm_16894677,33851330,学习这门课程让我有了大学系统学习英语的感觉，系统又细致的课程让我觉得很适合重新学习遗忘了很久...,2020-11-17 20:38:12,"[0.7135210633277893, -0.22205057740211487, 0.0..."
1,Cm_16894684,36508734,不是，因为体育简单来说就是要动起来，但是电子竞技不需要运动,2020-11-17 20:38:18,"[0.5384112596511841, 0.4153485596179962, -0.33..."
2,Cm_16894688,36727092,"增加知名度，普及体育活动通知,宣传，推广，促进体育发展",2020-11-17 20:38:19,"[-0.06789788603782654, -0.2426445335149765, -0..."
3,Cm_16894714,36357785,知母能泻肺火而滋肾，故不仅能清实热，且可清虚热，在临床上多与黄柏同用，配入滋阴药中，如知柏地...,2020-11-17 20:38:27,"[0.4234633147716522, 0.31170517206192017, -1.3..."
4,Cm_16894723,35676913,装备悬殊的情况下，环境恶劣的情况下，我军取得胜利靠的正是坚强的意志，不惧牺牲的勇气，爱国的热情。,2020-11-17 20:38:31,"[0.9780874848365784, 0.1317300647497177, -0.33..."
...,...,...,...,...,...
10685,Cm_17041954,4141841,从幼儿园到现在大学生活2.学到了很多东西，认识了很多人3.自己合理安排4.看书，查阅资料,2020-11-19 01:12:42,"[0.8197593688964844, -0.7414008975028992, 0.44..."
10686,Cm_17042024,31293967,经济上相互利用，政治上对立,2020-11-19 01:16:48,"[0.09364138543605804, 0.17872440814971924, -0...."
10687,Cm_17042077,33852476,《黄鹤楼》崔颢昔人已乘黄鹤去，此地空余黄鹤楼。黄鹤一去不复返，白云千载空悠悠。晴川历历汉阳树...,2020-11-19 01:20:05,"[0.40063828229904175, 0.36548176407814026, -0...."
10688,Cm_17042100,33234661,"不定冠词a,an定冠词the",2020-11-19 01:21:23,"[-1.2296175956726074, -0.39053255319595337, -0..."


In [65]:
comment_o = {
    "id_min":23,
    "id_max":17042101
}

In [66]:
data["comment"] =comment_o

In [67]:
for key, value in data.items():
    print(f'Key: {key}')

Key: course
Key: use
Key: school
Key: teacher
Key: problem
Key: comment


### 合并保存

In [68]:
with open('F:\\mooccubex\\csv\\data_overview.json', 'w', encoding='utf-8') as file:
    json.dump(data, file,ensure_ascii=False, indent=4)